name: Test & Coverage

on: [push]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Use Checkout 4
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Use pnpm 8
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true

            - name: Run tests
              run: pnpm test

            - name: Use Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
