name: Test & Coverage
on: [push]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Use Checkout 3
              uses: actions/checkout@v3

            - name: Use Node.js 19
              uses: actions/setup-node@v1
              with:
                  node-version: 19.x

            - name: Use pnpm 8
              uses: pnpm/action-setup@v2
              with:
                  version: 8.x
                  run_install: true

            - name: Run tests
              run: pnpm test

            - name: Use Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
